Feature/customer management
ereticor/Platform pull request #3
Opened 2022-01-17 13:34 UTC by ereticor

created customer management module
minor changes: 
  basic fetch API for creating requests
  fetch API for customer service
  simple error page when server request fails
  progress spinner for data loading 
  universal table for any object data
  customer table with helper to format customer data
  customer profile and edit pages

![image](https://user-images.githubusercontent.com/79747854/149777596-1441d66f-b751-4b00-a68f-4cd73f5f5564.png)
![image](https://user-images.githubusercontent.com/79747854/149777665-b2de654b-d549-42e4-964d-bfee029e5cb1.png)

2022-01-25 19:14 UTC, kommbatsoon requested changes

2022-01-25 19:14 UTC, kommbatsoon commented on src/modules/customerManagement/CustomerDetails/CustomerDetails.tsx
> +            cancelHandler={() => deleteCustomer(customer.id)}
It's better to provide config. You have `deleteCustomer` for `cancelHandler` looks strange

2022-01-25 19:14 UTC, kommbatsoon commented on src/modules/customerManagement/CustomerEdit/CustomerEdit.tsx
> +  const handleCustomerCreation = async (name: string) => {
handleCustomerCreate
handleCustomerUpdate
handleCustomerDelete

2022-01-25 19:14 UTC, kommbatsoon commented on src/modules/customerManagement/CustomerEdit/CustomerEdit.tsx
> +        {mode === "edit" ? (
Same about ternary operator

2022-01-25 19:14 UTC, kommbatsoon commented on src/modules/customerManagement/CustomerProfileWrapper/CustomerProfileWrapper.tsx
> +import "./CustomerProfileWrapper.scss";
It's better to have CustomerDetails

2022-01-25 19:14 UTC, kommbatsoon commented on src/modules/customerManagement/CustomerTable/CustomerTable.tsx
> +  const [searchName, setSearch] = useState(
potentially you can have an unlimited amount of filters such as `search, page, pageSize`. It's better to have an object for all of it, f.e. `filter`

2022-01-25 19:14 UTC, kommbatsoon commented on src/services/customer.service.ts
> +  static async changeCustomer({ customerId, newData }: IChangeCustomer) {
Usually, it's called `update `

2022-01-25 19:17 UTC, kommbatsoon commented
LGTM, but with some minor comments.

Points to discuss:
- naming
- conditional rendering (ternary operator is not the only option)
- file placement

2022-01-26 07:41 UTC, ereticor commented on src/components/DataTable/DataTable.tsx
> +interface IDataTable {
renamed as rowActions ✔

2022-01-26 07:44 UTC, ereticor commented on src/components/DataTable/DataTable.tsx
> +          rowsPerPageOptions={[10, 20, 30]}
reworked as an optional prop with default values ([10, 20, 30]) ✔

2022-01-26 07:51 UTC, ereticor commented on src/services/api.service.ts
> +            // this.redirectToErrorPage(reqErrors.SERVER_TROUBLE);
commented due to server errors caused by PUT/DELETE requests 
this occurs some times, so redirect was commented out priop to work on the error pages

2022-01-26 07:56 UTC, ereticor commented on src/services/customer.service.ts
> +  static async changeCustomer({ customerId, newData }: IChangeCustomer) {
renamed as updateCustomer ✔

2022-01-26 08:01 UTC, ereticor commented on src/store/reducers/customer/actionTypes.ts
> +export const getAllCustomersTypes = {
types named due to request type
**_discussion_**

2022-01-26 08:06 UTC, ereticor commented on src/components/AsideNavigation/AsideNavigation.tsx
> +                `aside__link ${isActive ? "link_active" : ""}`
![image](https://user-images.githubusercontent.com/79747854/151125412-a6bf0f49-3735-4433-b90b-ad05c3a4f686.png)
![image](https://user-images.githubusercontent.com/79747854/151125420-4c14c2a1-a01d-4d4a-9366-b73a33953f82.png)
activeClassName is now deprecated (react-router v6, this is the official active class implementation)

2022-01-26 08:12 UTC, ereticor commented on src/store/reducers/customer/actions.ts
> +export const getPage = ({
I would rather change it just a tiny bit, something like "getPaged" or "getCustomersList"
**_discussion_**

2022-01-26 08:17 UTC, ereticor commented on src/components/DataTable/DataTableActions.tsx
> +const CONFIG = {
I used RMT as a reference for the table actions. CONFIG was placed inside a component file. But I can freely move it to constants/config or create config folder/file for that purpose
**_discussion_**

2022-01-26 08:19 UTC, ereticor commented on src/components/DataTable/DataTableActions.tsx
> +                    ? (e) => handleClick(e as unknown as MouseEvent, action)
cause of typing issues (typing as event requires to insert props of that event / make event as unknown first)
![image](https://user-images.githubusercontent.com/79747854/151127164-e81785cb-85ca-49b2-8a5e-d79e0000061c.png)

2022-01-26 08:26 UTC, ereticor commented on src/components/DataTable/DataTable.tsx
> +          count={dataCount}
renamed as "totalCount" ✔
[https://github.com/ereticor/Platform/pull/3/commits/76fc4391f26bbc0cabd1833c7a908fd3e919c601](commit)

2022-01-26 08:26 UTC, ereticor commented on src/components/FormControls/FormControls.tsx
> +const FormControls = ({
renamed as "FormFooter" ✔
[https://github.com/ereticor/Platform/pull/3/commits/8d083d98570f36270b70ea07a63bed88fdb26aff](commit)

2022-01-26 08:33 UTC, ereticor commented on src/helpers/capitalizeString.ts
> +export default (str: string): string => {
that function is not for style purposes, but rather for request params capitalization (as API needs "Page", not "page"). But your name suggestion is write about what id does.
renamed as "capitalizeFirstString" ✔
[commit](https://github.com/ereticor/Platform/pull/3/commits/3bf067a52ace6012e703e8b4371026ea4978a2f3)

2022-01-26 08:37 UTC, ereticor commented on src/modules/customerManagement/CustomerEdit/CustomerEdit.tsx
> +  const handleCustomerCreation = async (name: string) => {
renamed as "handleCustomerCreate" ✔
[commit](https://github.com/ereticor/Platform/pull/3/commits/6d2eb525893f06a35ffb44476cc7ad5b52be2d86)

2022-01-26 08:40 UTC, ereticor commented on src/modules/customerManagement/CustomerProfileWrapper/CustomerProfileWrapper.tsx
> +import "./CustomerProfileWrapper.scss";
did you mean changing component naming for "customerDetailsWrapper (because CustomerDetails is a separate component)?
**_discussion_**

2022-01-26 08:46 UTC, ereticor commented on src/modules/customerManagement/CustomerDetails/CustomerDetails.tsx
> +            cancelHandler={() => deleteCustomer(customer.id)}
**_discussion_**

2022-01-26 11:37 UTC, kommbatsoon commented on src/modules/customerManagement/CustomerEdit/CustomerEdit.tsx
> +  const [customerName, setCustomerName] = useState(customer.name || "");
Move to formValue or smth

2022-01-26 12:57 UTC, ereticor commented on src/interfaces/api.service.ts
> +export interface IRequest {
![image](https://user-images.githubusercontent.com/79747854/151166482-49843bef-481a-4c4c-861b-c4a00a7efbea.png)
api interfaces using common templates as you mention (like "api.*yourAPI*.ts"), but without "interface" in its naming cause of their disposal at "interfaces" folder

2022-01-26 13:03 UTC, ereticor commented on src/modules/customerManagement/CustomerProfileWrapper/CustomerProfileWrapper.tsx
> +import "./CustomerProfileWrapper.scss";
renamed as "customerDetailsWrapper" ✔
[commit](https://github.com/ereticor/Platform/pull/3/commits/b416ddf3423df2718ec9b60784503b8c2a527d0e)

2022-01-26 13:40 UTC, ereticor commented on src/modules/customerManagement/CustomerEdit/CustomerEdit.tsx
> +  const [customerName, setCustomerName] = useState(customer.name || "");
moved huge chunk ternars to separate jsx-elements
CustomerEdit+CustomerDetails+FormFooter components changed (resolves other suggestions) 
[commit](https://github.com/ereticor/Platform/pull/3/commits/57737968253e0a0fff86fc37ae883a926b76aae3)

2022-01-26 13:41 UTC, ereticor commented on src/modules/customerManagement/CustomerDetails/CustomerDetails.tsx
> +      {customer ? (
resolved in other suggestion node

2022-01-26 13:43 UTC, ereticor commented on src/modules/customerManagement/CustomerEdit/CustomerEdit.tsx
> +        {mode === "edit" ? (
moved huge chunk ternars to separate jsx-elements
CustomerEdit+CustomerDetails+FormFooter components changed (resolves other suggestions)
commit

2022-01-26 13:45 UTC, kommbatsoon commented on src/components/FormFooter/FormFooter.tsx
> +      onClick={() => (submitHandler ? submitHandler(submitValue) : false)}
If no `submitHandler `provided I think you don't need to render the whole `button`

2022-01-26 13:45 UTC, kommbatsoon commented on src/modules/customerManagement/CustomerEdit/CustomerEdit.tsx
>          title={mode === "edit" ? "update customer" : "create customer"}
Move to variable like `isEditMode`

2022-01-26 14:19 UTC, ereticor commented on src/modules/customerManagement/CustomerEdit/CustomerEdit.tsx
>          title={mode === "edit" ? "update customer" : "create customer"}
moved to separate variable "isEditMode" ✔
[commit](https://github.com/ereticor/Platform/pull/3/commits/94653a9bb4817ec0996b977f9bfee54105f85188)

2022-01-26 14:20 UTC, ereticor commented on src/components/FormFooter/FormFooter.tsx
> +      onClick={() => (submitHandler ? submitHandler(submitValue) : false)}
rework form footer buttons behavior (no cancel/submit links, only handlers that can call navigation to other pages) ✔
[commit](https://github.com/ereticor/Platform/pull/3/commits/e9cdf0e401392af277c75523d8fac0ddf3c83c7c)

2022-01-27 08:24 UTC, ereticor commented on src/components/FormControls/FormControls.tsx
> +      <Button
resolved in subsequent node ✔

2022-01-27 08:31 UTC, ereticor commented on src/components/AsideNavigation/AsideNavigation.tsx
> +                `aside__link ${isActive ? "link_active" : ""}`
added classname builder helper ✔
[commit](https://github.com/ereticor/Platform/pull/3/commits/d275efc7120be17fcf24be7e6ed0586910cd0158)

2022-01-27 09:12 UTC, ereticor commented on src/components/DataTable/DataTableActions.tsx
> +const CONFIG = {
moved to separate config folder (table -> table actions, table headers) ✔
[commit](https://github.com/ereticor/Platform/pull/3/commits/40d4f814b4ed05e389feda6cbb5d67e94a8906c6)

2022-01-27 09:20 UTC, ereticor commented on src/components/DataTable/DataTableActions.tsx
> +                    ? (e) => handleClick(e as unknown as MouseEvent, action)
changed to React.MouseEvent ✔
[commit](https://github.com/ereticor/Platform/pull/3/commits/2ae892a055a341e78a29bd458d138497a702c942)

2022-01-27 11:15 UTC, ereticor commented on src/helpers/getDisplayedValue/index.ts
> +      return data[header.prop] || "-";
added max size & title options for value formatter ✔
[commit](https://github.com/ereticor/Platform/pull/3/commits/c344343272caf90aaaab9003b13be2986a545865)

2022-01-27 12:02 UTC, ereticor commented on src/modules/customerManagement/CustomerEdit/CustomerEdit.tsx
> +  const [customerName, setCustomerName] = useState(customer.name || "");
changed form creation & createCustomer api function ✔
[commit](https://github.com/ereticor/Platform/pull/3/commits/0be27925a7777fdd51e0b0bc4c4d36c2dacdfd4c)

2022-01-27 14:12 UTC, merged